### ISSUE TITLE
[Epic] Add Input Manager

### ISSUE THREAD

**Issue by ghost** [vlad-ostas/peanuts#23]
- [ ] Check for existing input managers, cross-platform maybe
- [ ] Make a draft scheme of how it works
- [ ] Make user interface imitating working program
- [ ] Make it actually work
